//
// Created by Elijah Crain on 10/5/25.
//

#ifndef CFR2_TEXAS_GAME_TRANSITIONER_HPP
#define CFR2_TEXAS_GAME_TRANSITIONER_HPP
#include <functional>
#include <variant>
#include <stdexcept>
#include <algorithm>

#include "BettingConfig.hpp"
#include "GameBase.hpp"
#include "Context/GameContext.hpp"
#include "GameState.hpp"

namespace Game {

using GameState = GameState;

// Transition result - actions now generated by policy, not transitioner
struct TransitionResult {
    GameState nextState;
    std::function<void(GameContext&)> sideEffect = nullptr;
};

class Transitioner {
public:
    Transitioner() = delete;

    static TransitionResult transition(const Action& action,
                                       const GameContext& context,
                                       const BettingConfig& config,
                                       const GameState& state) {
        return std::visit([&](const auto& s) {
            return process(action, context, config, s);
        }, state);
    }

private:
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const ChanceState& state);
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const ActionState& state);
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const TerminalState& state);

    static TransitionResult makeTerminal(const GameContext& context, int winner,
                                         double pot, TerminalState::Reason reason);
};

// Implementation
inline TransitionResult Transitioner::process([[maybe_unused]] const Action& action,
                                              [[maybe_unused]] const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              const ChanceState& state)
{
    TransitionResult result;

    ActionState nextState;
    if (state.type == ChanceState::DEAL_HOLE) {
        nextState = ActionState{.currentBet = 500};
    } else {
        nextState = ActionState{};
    }

    result.nextState = nextState;
    result.sideEffect = [](GameContext& ctx) {
        ctx.setRoundStartingPlayer();
    };

    return result;
}

inline TransitionResult Transitioner::process(const Action& action, const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              const ActionState& state) {
    return std::visit([&context, &state]<typename ActionType>(const ActionType& act) -> TransitionResult {
        using T = std::decay_t<ActionType>;

        if constexpr (std::is_same_v<T, Check>) {
            if (context.isPreflop() || state.checksCount == NUM_PLAYERS - 1) {
                if (!context.isRiver()) {
                    return {
                        .nextState = ChanceState{},
                        .sideEffect = [](GameContext& ctx) { ctx.advanceRound(); }
                    };
                } else {
                    return makeTerminal(context, -1, context.getPot(), TerminalState::SHOWDOWN);
                }
            } else {
                auto newState = state;
                newState.checksCount++;
                newState.firstActionTaken = true;
                return {
                    .nextState = newState,
                    .sideEffect = [](GameContext& ctx) { ctx.nextPlayer(); }
                };
            }
        }
        else if constexpr (std::is_same_v<T, Raise>) {
            ActionState newState;
            newState.currentBet = act.amount;
            newState.raiseCount = state.raiseCount + 1;
            newState.lastRaiser = context.getCurrentPlayer();
            newState.firstActionTaken = true;

            return {
                .nextState = newState,
                .sideEffect = [amt = act.amount](GameContext& ctx) {
                    ctx.addMoney(ctx.getCurrentPlayer(), amt, false);
                    ctx.nextPlayer();
                }
            };
        }
        else if constexpr (std::is_same_v<T, Fold>) {
            return makeTerminal(context, 1 - context.getCurrentPlayer(), context.getPot(), TerminalState::FOLD);
        }
        else if constexpr (std::is_same_v<T, Call>) {
            if (!state.firstActionTaken) {
                // Handle limp
                auto newState = state;
                newState.firstActionTaken = true;
                return {
                    .nextState = newState,
                    .sideEffect = [amt = act.amount](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                        ctx.nextPlayer();
                    }
                };
            } else {
                uint32_t callerStack = context.getStack(context.getCurrentPlayer());
                uint32_t betToCall = state.currentBet;

                if (context.isPreflop() &&
                    state.raiseCount == 1 &&
                    state.lastRaiser == 1)
                {
                    betToCall -= 500;
                }

                bool isAllIn = act.amount >= callerStack || act.amount < betToCall;

                if (isAllIn) {
                    double amountToReturn = betToCall - act.amount;
                    const int raiser_player = 1 - context.getCurrentPlayer();

                    if (context.getStack(raiser_player) == 0) {
                        amountToReturn = 0;
                    }

                    auto result = makeTerminal(context, -1, context.getPot() + act.amount, TerminalState::SHOWDOWN);
                    result.sideEffect = [amt = act.amount, amountToReturn](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                        if (amountToReturn > 0) {
                            const int raiser = 1 - ctx.getCurrentPlayer();
                            ctx.updateStack(raiser, amountToReturn);
                            ctx.updatePot(-amountToReturn);
                        }
                    };
                    return result;
                }

                if (!context.isRiver()) {
                    return {
                        .nextState = ChanceState{},
                        .sideEffect = [amt = act.amount](GameContext& ctx) {
                            ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                            ctx.advanceRound();
                        }
                    };
                } else {
                    auto result = makeTerminal(context, -1, context.getPot() + act.amount, TerminalState::SHOWDOWN);
                    result.sideEffect = [amt = act.amount](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                    };
                    return result;
                }
            }
        } else {
            throw std::logic_error("Invalid action for ActionState");
        }
    }, action);
}

inline TransitionResult Transitioner::process([[maybe_unused]] const Action& action,
                                              [[maybe_unused]] const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              [[maybe_unused]] const TerminalState& state)
{
    throw std::logic_error("Cannot transition from terminal state");
}

inline TransitionResult Transitioner::makeTerminal(const GameContext& context,
                                                   const int winner,
                                                   double pot,
                                                   const TerminalState::Reason reason)
{
    TerminalState terminal;
    terminal.pot = pot;
    terminal.reason = reason;

    if (reason != TerminalState::SHOWDOWN) {
        terminal.winner = winner;
    } else {
        uint64_t player0Hand =context.getCardHash(0,3);
        uint64_t player1Hand = context.getCardHash(1,3);
        if (player0Hand == player1Hand) { //compare river hands
            terminal.winner = 2;
        } else {
            terminal.winner = player0Hand > player1Hand ? 0 : 1;
        }
    }
    return {
        .nextState = terminal,
        .sideEffect = nullptr
    };
}

}  // namespace Game

#endif  // CFR2_TEXAS_GAME_TRANSITIONER_HPP