//
// Created by Elijah Crain on 10/5/25.
//

#ifndef CFR2_TEXAS_GAME_TRANSITIONER_HPP
#define CFR2_TEXAS_GAME_TRANSITIONER_HPP
#include <functional>
#include <variant>
#include <stdexcept>
#include <algorithm>

#include "BettingConfig.hpp"
#include "GameBase.hpp"
#include "Context/GameContext.hpp"
#include "GameState.hpp"
#include "Utility/Utility.hpp"

namespace Game {

using GameState = GameState;

// Transition result - actions now generated by policy, not transitioner
struct TransitionResult {
    GameState nextState;
    std::function<void(GameContext&)> sideEffect = nullptr;
};

class Transitioner {
public:
    Transitioner() = delete;

    static TransitionResult transition(const Action& action,
                                       const GameContext& context,
                                       const BettingConfig& config,
                                       const GameState& state) {
        return std::visit([&](const auto& s) {
            return process(action, context, config, s);
        }, state);
    }

private:
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const ChanceState& state);
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const ActionState& state);
    static TransitionResult process(const Action& action, const GameContext& context,
                                    const BettingConfig& config, const TerminalState& state);

    static TransitionResult makeTerminal(const GameContext& context, int winner,
                                         double pot, TerminalState::Reason reason);
};

// Implementation
inline TransitionResult Transitioner::process([[maybe_unused]] const Action& action,
                                              [[maybe_unused]] const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              const ChanceState& state)
{
    TransitionResult result;

    ActionState nextState;
    if (state.type == ChanceState::DEAL_HOLE) {
        nextState = ActionState{.currentBet = 500};
    } else {
        nextState = ActionState{};
    }

    result.nextState = nextState;
    result.sideEffect = [](GameContext& ctx) {
        ctx.setRoundStartingPlayer();
    };

    return result;
}

inline TransitionResult Transitioner::process(const Action& action, const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              const ActionState& state) {
    return std::visit([&context, &state]<typename ActionType>(const ActionType& act) -> TransitionResult {
        using T = std::decay_t<ActionType>;

        if constexpr (std::is_same_v<T, Check>) {
            if (context.isPreflop() || state.checksCount == NUM_PLAYERS - 1) {
                if (!context.isRiver()) {
                    return {
                        .nextState = ChanceState{},
                        .sideEffect = [](GameContext& ctx) { ctx.advanceRound(); }
                    };
                } else {
                    return makeTerminal(context, -1, context.getPot(), TerminalState::SHOWDOWN);
                }
            } else {
                auto newState = state;
                newState.checksCount++;
                newState.firstActionTaken = true;
                return {
                    .nextState = newState,
                    .sideEffect = [](GameContext& ctx) { ctx.nextPlayer(); }
                };
            }
        }
        else if constexpr (std::is_same_v<T, Raise>) {
            ActionState newState;
            newState.currentBet = act.amount;
            newState.raiseCount = state.raiseCount + 1;
            newState.lastRaiser = context.getCurrentPlayer();
            newState.firstActionTaken = true;

            return {
                .nextState = newState,
                .sideEffect = [amt = act.amount](GameContext& ctx) {
                    ctx.addMoney(ctx.getCurrentPlayer(), amt, false);
                    ctx.nextPlayer();
                }
            };
        }
        else if constexpr (std::is_same_v<T, Fold>) {
            return makeTerminal(context, 1 - context.getCurrentPlayer(), context.getPot(), TerminalState::FOLD);
        }
        else if constexpr (std::is_same_v<T, Call>) {
            if (!state.firstActionTaken) {
                // Handle limp
                auto newState = state;
                newState.firstActionTaken = true;
                return {
                    .nextState = newState,
                    .sideEffect = [amt = act.amount](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                        ctx.nextPlayer();
                    }
                };
            } else {
                uint32_t callerStack = context.getStack(context.getCurrentPlayer());
                uint32_t betToCall = state.currentBet;

                if (context.isPreflop() &&
                    state.raiseCount == 1 &&
                    state.lastRaiser == 1)
                {
                    betToCall -= 500;
                }

                bool isAllIn = act.amount >= callerStack || act.amount < betToCall;

                if (isAllIn) {
                    double amountToReturn = betToCall - act.amount;
                    const int raiser_player = 1 - context.getCurrentPlayer();

                    if (context.getStack(raiser_player) == 0) {
                        amountToReturn = 0;
                    }

                    auto result = makeTerminal(context, -1, context.getPot() + act.amount, TerminalState::SHOWDOWN);
                    result.sideEffect = [amt = act.amount, amountToReturn](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                        if (amountToReturn > 0) {
                            const int raiser = 1 - ctx.getCurrentPlayer();
                            ctx.updateStack(raiser, amountToReturn);
                            ctx.updatePot(-amountToReturn);
                        }
                    };
                    return result;
                }

                if (!context.isRiver()) {
                    return {
                        .nextState = ChanceState{},
                        .sideEffect = [amt = act.amount](GameContext& ctx) {
                            ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                            ctx.advanceRound();
                        }
                    };
                } else {
                    auto result = makeTerminal(context, -1, context.getPot() + act.amount, TerminalState::SHOWDOWN);
                    result.sideEffect = [amt = act.amount](GameContext& ctx) {
                        ctx.addMoney(ctx.getCurrentPlayer(), amt, true);
                    };
                    return result;
                }
            }
        } else {
            throw std::logic_error("Invalid action for ActionState");
        }
    }, action);
}

inline TransitionResult Transitioner::process([[maybe_unused]] const Action& action,
                                              [[maybe_unused]] const GameContext& context,
                                              [[maybe_unused]] const BettingConfig& config,
                                              [[maybe_unused]] const TerminalState& state)
{
    throw std::logic_error("Cannot transition from terminal state");
}

inline TransitionResult Transitioner::makeTerminal(const GameContext& context,
                                                   const int winner,
                                                   double pot,
                                                   const TerminalState::Reason reason)
{
    TerminalState terminal;
    terminal.pot = pot;
    terminal.reason = reason;

    if (reason != TerminalState::SHOWDOWN) {
        terminal.winner = winner;
    } else {
        // Showdown: evaluate both 7-card hands with the TwoPlusTwo lookup
        // and pick the higher rank. The previous code compared
        // hand_indexer outputs — those are *canonical-form identifiers*,
        // not strength scores, so the resulting winner was effectively
        // arbitrary. That bug was leaking into the PPO reward signal on
        // every showdown.
        //
        // Card encoding conversion: deck.h stores cards as
        //   id_dh = (rank << 2) | suit_dh    rank ∈ [0, 13), suit ∈ [0, 4)
        // with suit table "shdc" → suit 0=s, 1=h, 2=d, 3=c.
        // The TwoPlusTwo evaluator (Ray Wotton's tables) uses
        //   id_2p2 = (rank * 4) + suit_2p2 + 1
        // with suit order "cdhs" → suit 0=c, 1=d, 2=h, 3=s. So
        //   suit_2p2 = 3 - suit_dh
        //   id_2p2   = (id_dh & ~3) + (3 - (id_dh & 3)) + 1
        const auto& raw = context.cards.rawCards;
        auto to_2p2 = [](uint8_t c) -> int {
            const int rank      = c >> 2;
            const int suit_dh   = c & 3;
            const int suit_2p2  = 3 - suit_dh;
            return rank * 4 + suit_2p2 + 1;
        };
        int p0_cards[7] = {
            to_2p2(raw[0]), to_2p2(raw[1]),                  // hole
            to_2p2(raw[4]), to_2p2(raw[5]), to_2p2(raw[6]),  // flop
            to_2p2(raw[7]),                                  // turn
            to_2p2(raw[8]),                                  // river
        };
        int p1_cards[7] = {
            to_2p2(raw[2]), to_2p2(raw[3]),
            to_2p2(raw[4]), to_2p2(raw[5]), to_2p2(raw[6]),
            to_2p2(raw[7]),
            to_2p2(raw[8]),
        };
        const int w = Utility::getWinner(p0_cards, p1_cards);
        // Utility::getWinner returns 0, 1, or 3 (tie). The Game's terminal
        // convention is winner=2 for tie.
        terminal.winner = (w == 3) ? 2 : w;
    }
    return {
        .nextState = terminal,
        .sideEffect = nullptr
    };
}

}  // namespace Game

#endif  // CFR2_TEXAS_GAME_TRANSITIONER_HPP